backend:
  name: github
  repo: RoomX24/RoomX  # ide írd a GitHub repo-d nevét pl. RoomX24/roomx

media_folder: "static/images/uploads"  # hova kerülnek a képek
public_folder: "/images/uploads"

collections:
  - name: "tippek"
    label: "Tippek"
    folder: "content"     # ide kell, hogy legyen egy mappád, pl. content/tippe
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Cím", name: "title", widget: "string" }
      - { label: "Szöveg", name: "body", widget: "text" }
